version: '3'

services:
  ctpn6852-server:
    image: ctpn6852/python:2.7.14
    ports:
    - "6853:6853"
    stdin_open: true #后台运行
    tty: true #后台运行
    privileged: true #用友真正的root权限
    environment:
      # 指定时区
      - TZ="Asia/Shanghai"
    container_name: ctpn6852-server
    volumes:
      - ./CTPN6852:/CTPN6852
    working_dir: /CTPN6852/api/
#    command: ["uwsgi","--ini","ctpn6852.ini"]
